name: Build jbig2enc Debian Packages
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'jbig2enc version tag to build'
        required: true
        type: string
        default: "0.30"
      testing:
        description: 'Testing mode (build only, no release)'
        required: false
        type: boolean
        default: false
env:
  # Make the input version available to all jobs
  JBIG2ENC_VERSION: ${{ inputs.version }}
jobs:
  # Job to build the .deb package for each architecture
  build-deb-package:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build jbig2enc Docker image
        run: |
          docker build \
            --tag "jbig2enc:${JBIG2ENC_VERSION}-${{ matrix.arch }}" \
            --build-arg JBIG2ENC_VERSION="${JBIG2ENC_VERSION}" \
            --file jbig2enc.dockerfile \
            --progress plain \
            .
        env:
          JBIG2ENC_VERSION: ${{ env.JBIG2ENC_VERSION }}
      - name: Extract built .deb package
        run: |
          image_id=$(docker create "jbig2enc:${JBIG2ENC_VERSION}-${{ matrix.arch }}")
          mkdir -p outputs/jbig2enc
          # Copy the built .deb files from the container to the host
          docker cp "${image_id}":/usr/src/jbig2enc/ outputs/
          # Clean up the created container
          docker rm "${image_id}"
          echo "Extracted files:"
          find outputs/jbig2enc -name "*.deb"
        env:
          JBIG2ENC_VERSION: ${{ env.JBIG2ENC_VERSION }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jbig2enc-deb-${{ env.JBIG2ENC_VERSION }}-${{ matrix.arch }}
          path: outputs/jbig2enc/*.deb
          retention-days: 7
  # Job to create a release and upload the .deb packages
  create-release:
    if: ${{ !inputs.testing }}
    needs: build-deb-package
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Prepare release artifacts
        run: |
          mkdir -p release-artifacts
          # Find all .deb files across all downloaded artifact directories
          find artifacts/ -name "*.deb" -exec cp {} release-artifacts/ \;
          echo "Files to be released:"
          ls -la release-artifacts/
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: jbig2enc-v${{ env.JBIG2ENC_VERSION }}
          commit: ${{ github.sha }}
          name: "jbig2enc v${{ env.JBIG2ENC_VERSION }} (Multi-arch)"
          artifacts: "release-artifacts/*.deb"
          prerelease: true
          draft: false
          replacesArtifacts: true
          body: |
            ## jbig2enc v${{ env.JBIG2ENC_VERSION }} Multi-architecture Debian Packages
            **Version:** ${{ env.JBIG2ENC_VERSION }}
            **Build Date:** ${{ steps.date.outputs.date }}
            **Commit:** ${{ github.sha }}
            **Actor:** ${{ github.actor }}
